import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#f8f8f8', // Light background
    alignItems: 'center',
    paddingVertical: 30,
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 30,
    color: '#333',
  },
  image: {
    width: '90%',
    height: 250,
    borderRadius: 12,
    marginVertical: 25,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: '#eee',
  },
  loader: {
    marginVertical: 20,
  },
  lottieAnimation: {
    width: 200,
    height: 200,
  },
  errorText: {
    color: '#d9534f',
    marginTop: 20,
    textAlign: 'center',
    fontSize: 16,
    paddingHorizontal: 20,
  },
  responseContainer: {
    marginTop: 30,
    padding: 25,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
  },
  recipeTitle: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
    color: '#222',
    lineHeight: 38,
  },
  homeRecipeTitle: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 10,
    color: '#222',
    lineHeight: 24,
  },
  recipeMetaData: {
    fontSize: 16,
    color: '#666',
    marginBottom: 20,
    textAlign: 'center',
  },
  recipeImage: {
    width: '100%',
    height: 200,
    borderRadius: 10,
    marginBottom: 10,
  },
  sectionContainer: {
    width: '90%',
    marginVertical: 10,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 15,
    color: '#333',
    borderBottomWidth: 2,
    borderBottomColor: '#f0f0f0',
    paddingBottom: 5,
    width: '100%',
  },
  table: {
    width: '100%',
    backgroundColor: '#fdfdfd',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#eee',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  tableHeaderText: {
    flex: 1,
    fontWeight: '700',
    textAlign: 'center',
    color: '#555',
    fontSize: 15,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f9f9f9',
  },
  tableCell: {
    flex: 1,
    textAlign: 'center',
    color: '#444',
    fontSize: 15,
  },
  button: {
    backgroundColor: '#0a8a00', // Instacart green
    paddingVertical: 14,
    paddingHorizontal: 25,
    borderRadius: 8,
    marginTop: 30,
    alignSelf: 'center',
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 5,
  },
  uploadButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listContainer: {
    width: '100%',
    paddingHorizontal: 10,
    marginTop: 5,
  },
  listItem: {
    fontSize: 16,
    marginBottom: 8,
    lineHeight: 22,
    color: '#444',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '90%',
  },
  fullImageModalContainer: {
    flex: 1,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    width: '100%',
    height: '100%',
  },
  closeButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    backgroundColor: 'rgba(255,255,255,0.5)',
    padding: 10,
    borderRadius: 5,
  },
  closeButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  cameraButton: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    backgroundColor: '#0a8a00',
    padding: 15,
    borderRadius: 50,
    elevation: 8,
  },
  listContent: {
    paddingTop: 50,
    paddingBottom: 100,
  },
  tooltipContainer: {
    position: 'absolute',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 8,
    borderRadius: 5,
    bottom: 10,
    alignSelf: 'center',
  },
  tooltipText: {
    color: 'white',
    fontSize: 12,
  },
  pickerModalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  pickerModalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    alignItems: 'center',
  },
  pickerOptionButton: {
    width: '100%',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    alignItems: 'center',
  },
  pickerOptionText: {
    fontSize: 18,
    color: '#007AFF',
  },
  pickerCancelButton: {
    width: '100%',
    padding: 15,
    marginTop: 10,
    alignItems: 'center',
  },
  pickerCancelText: {
    fontSize: 18,
    color: '#FF3B30',
    fontWeight: 'bold',
  },
  emptyRecipesContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    textAlign: 'center',
  },
  emptyRecipesText: {
    fontSize: 18,
    color: '#666',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 30,
    lineHeight: 24,
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 15,
  },
  tag: {
    backgroundColor: '#e0e0e0',
    color: '#333',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 15,
    margin: 5,
    fontSize: 14,
    overflow: 'hidden',
  },
});